baseURL: "https://vrusso.com.br/"
title: Vicente Russo Neto
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

params:
    description: ""
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Vicente Russo Neto
          subtitle: "Full Stack Developer with expertise in cloud services and scalability. Committed to problem-solving, focusing on efficient and innovative solutions. Enthusiastic Game and Mobile Developer.<br><br>I ship code at OrthoDontic, SevenSails, PixelCrate Games, and PantheonBots. "
          imageUrl: "1690339340109.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Vicente Russo Neto
          buttons:
            - name: Seven Sails
              url: https://www.sevensails.com.br
            - name: Pixel Crate
              url: https://www.pixelcrate.games
            - name: PantheonBots
              url: https://www.pantheonbots.trade
    socialIcons:
        #- name: CV
        #  url: cv.pdf
        - name: Email
          url: mailto:vicente.russo@gmail.com
        - name: GitHub
          url: https://github.com/vicenterusso

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Vicente Russo"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
